### ISSUE TITLE
Feature Request : Extentsion List instead of single extension.

### ISSUE THREAD

**Issue by Anvesh2013** [pltnk/selective_copy#7]
We can have multiple extensions ,that'll be copied. 
Eg: I have a movies folder, and I want to copy mkv, mp4, srt, ass etc files with folder structure preserved, while omitting jpg, txt, nfo, etc.
We'd have to run the command multiple times with each extension if not.

**Comment by pltnk** [comment]
Yeas, we can! I was thinking about it from the beginning and now it's time to finally make it. I will add this feature in the next release. You are welcome to contribute if you want :)

**Comment by Anvesh2013** [comment]
Yes, I'd love to contribute, but I am new to this. I feel like I'll be slowing you down.
Also, we should probably add an --invert to the ext list option. --i [txt] would copy everything except txt format.

**Comment by pltnk** [comment]
Don't worry, I am new to this too, take your time. You have great ideas and it is a good opportunity to work on a real open source project and learn. Also you can just fork this repo and work at comfortable pace. 

And I guess it is better to open a new feature request for your suggestion.

**Comment by Anvesh2013** [comment]
Can we talk somewhere.. This is too slow.. FB Messenger, Whatsapp or something?

**Comment by Anvesh2013** [comment]
I think I implemented the list of extensions. We have to pass extensions like exe,py,png in the cmdline. We'll parse it to make a list, and walk over it. I don't understand enough Git to proceed though.

**Comment by pltnk** [comment]
I guess you can open a pull request and I will review your code.

**Comment by pltnk** [comment]
Feature is added via merging pull request #12
