### ISSUE TITLE
Feature Request :  Extension list with an invert option.

### ISSUE THREAD

**Issue by Anvesh2013** [pltnk/selective_copy#8]
It's useful to copy all files while omitting a couple extensions sometimes.. an invert option there would be useful.
slcp [txt] --invert would copy all files except txt files. Useful when there are many other extensions.

**Comment by fjcamillo** [comment]
I think blacklist / whitelist could also be a better name for it

**Comment by Anvesh2013** [comment]
> 
> 
> I think blacklist / whitelist could also be a better name for it

Yeah, something like that.. You'd know better than I.

**Comment by Anvesh2013** [comment]
I think I implemented the invert option. Tested it on a single folder. But I don't know how robust it is. How do I proceed here? Would you be taking a look?
